plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.5'
	id 'io.spring.dependency-management' version '1.1.5'
	id 'com.github.node-gradle.node' version '7.0.1'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	runtimeOnly 'org.postgresql:postgresql'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

node {
	version = '18.17.0'
	npmVersion = '9.6.7'
	download = true
	nodeProjectDir = file('src/main/resources/frontend')
}

task buildFrontend(type: NpmTask) {
	description = 'Build React frontend'
	args = ['run', 'build']
	outputs.dir('src/main/resources/static')
}

task npmInstall(type: NpmTask) {
	description = 'Install npm dependencies'
	args = ['install', '--legacy-peer-deps']
}

buildFrontend.dependsOn npmInstall

processResources.dependsOn buildFrontend

tasks.register('copyFrontendDist') {
	dependsOn buildFrontend
	doLast {
		copy {
			from 'src/main/resources/frontend/dist'
			into 'src/main/resources/static'
		}
	}
}

processResources.finalizedBy copyFrontendDist

bootJar {
	archiveFileName = 'free-market-backend-0.0.1-SNAPSHOT.jar'
}
