spring.datasource.url=jdbc:postgresql://localhost:5432/free_market123
spring.datasource.username=student
spring.datasource.password=himitu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
